import React, { useEffect, useState } from "react";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { ServerUrl } from "../App";
import axios from "axios";
import toast from "react-hot-toast";
import { FaImages, FaUser, FaExternalLinkAlt } from "react-icons/fa";
import { HiSparkles } from "react-icons/hi";
import { useNavigate } from "react-router-dom";

const Community = () => {
  const [images, setImages] = useState([]);
  const [loading, setLoading] = useState(true);
  const navigate = useNavigate();

  const fetchImages = async () => {
    try {
      const { data } = await axios.get(`${ServerUrl}/api/community/published-images`);
      if (data.success) {
        setImages(data.images || []);
      } else {
        toast.error(data.message || "Failed to fetch images");
      }
    } catch (error) {
      console.error("Community images error:", error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchImages();
  }, []);

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 text-slate-900 dark:text-slate-100 flex flex-col transition-colors duration-300">
      <Navbar />

      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 pt-24 pb-16">
        <div className="mb-6 flex items-center justify-between">
          <span className="text-xs font-bold text-slate-500 dark:text-slate-400">
            Statistical Infographics
          </span>
        </div>

        <div className="text-center max-w-2xl mx-auto mb-12">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-blue-50 dark:bg-blue-950/80 border border-blue-200/80 dark:border-blue-800 text-blue-700 dark:text-blue-300 text-xs font-bold tracking-wide uppercase mb-4 shadow-xs">
            <FaImages className="text-blue-500" />
            <span>Community Gallery</span>
          </div>

          <h1 className="text-3xl sm:text-5xl font-black text-slate-900 dark:text-white tracking-tight">
            AI Statistical & Visual{" "}
            <span className="bg-gradient-to-r from-blue-600 via-indigo-600 to-violet-600 bg-clip-text text-transparent">
              Infographics
            </span>
          </h1>

          <p className="mt-3 text-slate-500 dark:text-slate-400 text-xs sm:text-sm leading-relaxed">
            Explore creative prompts, survey data charts, and statistical diagrams generated by officers using SankhyaIQ Studio.
          </p>

          <div className="mt-6">
            <button
              onClick={() => navigate("/ai-models")}
              className="inline-flex items-center gap-2 px-6 py-3 rounded-2xl bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white font-bold text-xs shadow-md hover:scale-105 active:scale-95 transition-all cursor-pointer"
            >
              <HiSparkles size={14} />
              <span>Explore AI Models & Workflows</span>
            </button>
          </div>
        </div>

        {/* Gallery Content */}
        {loading ? (
          <div className="grid gap-5 grid-cols-2 sm:grid-cols-3 lg:grid-cols-4">
            {[1, 2, 3, 4, 5, 6, 7, 8].map((n) => (
              <div
                key={n}
                className="h-60 rounded-3xl bg-slate-200 dark:bg-slate-800/60 animate-pulse border border-slate-300/40 dark:border-slate-700/50"
              />
            ))}
          </div>
        ) : images.length > 0 ? (
          <div className="grid gap-5 sm:gap-6 grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 2xl:grid-cols-5">
            {images.map((item, index) => (
              <a
                key={item._id || index}
                href={item.imageUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="group relative block rounded-3xl overflow-hidden bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 shadow-md hover:shadow-xl hover:-translate-y-1.5 transition-all duration-300"
              >
                <div className="relative aspect-square overflow-hidden bg-slate-100 dark:bg-slate-800">
                  <img
                    src={item.imageUrl}
                    alt="AI Infographic"
                    className="w-full h-full object-cover group-hover:scale-108 transition-transform duration-500 ease-out"
                    loading="lazy"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-slate-950/80 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end p-4">
                    <div className="flex items-center justify-between w-full text-white text-xs">
                      <span className="flex items-center gap-1.5 font-medium truncate pr-2">
                        <FaUser size={10} className="text-blue-300 shrink-0" />
                        <span className="truncate">{item.userName || "Officer"}</span>
                      </span>
                      <FaExternalLinkAlt size={11} className="text-slate-300 shrink-0" />
                    </div>
                  </div>
                </div>

                <div className="p-3.5 flex items-center justify-between text-xs text-slate-600 dark:text-slate-300">
                  <span className="font-bold text-slate-900 dark:text-white truncate">
                    {item.userName || "Statistical Officer"}
                  </span>
                  <span className="text-[10px] text-slate-400">SankhyaIQ</span>
                </div>
              </a>
            ))}
          </div>
        ) : (
          <div className="text-center py-16 px-4 bg-white/90 dark:bg-slate-900/90 rounded-3xl border border-slate-200 dark:border-slate-800 max-w-md mx-auto shadow-sm">
            <div className="w-16 h-16 rounded-2xl bg-blue-50 dark:bg-blue-950 text-blue-600 dark:text-blue-400 flex items-center justify-center mx-auto mb-4">
              <FaImages size={28} />
            </div>
            <h3 className="text-lg font-bold text-slate-900 dark:text-white">No Visual Artefacts Yet</h3>
            <p className="text-slate-500 dark:text-slate-400 text-xs mt-1">
              Be the first to generate and share official infographics from the AI Assistant Studio!
            </p>
          </div>
        )}
      </main>
      <Footer />
    </div>
  );
};

export default Community;
